# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: unifmu_handshake.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'unifmu_handshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16unifmu_handshake.proto\x12\x10unifmu_handshake\"\x12\n\x10HandshakeRequest\"C\n\x0eHandshakeReply\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.unifmu_handshake.HandshakeStatus*<\n\x0fHandshakeStatus\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42\x13\n\x00\x42\x0fUnifmuHandshakeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unifmu_handshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\000B\017UnifmuHandshake'
  _globals['_HANDSHAKESTATUS']._serialized_start=133
  _globals['_HANDSHAKESTATUS']._serialized_end=193
  _globals['_HANDSHAKEREQUEST']._serialized_start=44
  _globals['_HANDSHAKEREQUEST']._serialized_end=62
  _globals['_HANDSHAKEREPLY']._serialized_start=64
  _globals['_HANDSHAKEREPLY']._serialized_end=131
# @@protoc_insertion_point(module_scope)
